"use client";

import { Geist, Geist_Mono } from "next/font/google";
import './globals.css';
import Image from "next/image";
import AvatarImg from "@/../public/Avatar.png";
import Link from "next/link";
import Head from "next/head";
import { useEffect, useState } from "react"; // 加上動畫控制

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  const [hasMounted, setHasMounted] = useState(false);

  useEffect(() => {
    setHasMounted(true);
  }, []);

  return (
    <html lang="en" className="font-cute bg-gradient-to-b from-pink-200 via-pink-100 to-purple-50 text-pink-800">
      <Head>
        <title>盧語宸的數位履歷</title>
        <meta name="description" content="Generated by create next app" />
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+TC&display=swap" rel="stylesheet" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inknut+Antiqua:wght@300;400;500;600;700;800;900&family=Noto+Sans+TC:wght@300&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden`}>
        <div className="w-screen h-screen flex items-center justify-center p-4 md:p-8">
          <div className="flex flex-col sm:flex-row w-full h-full max-w-[1600px] gap-5">
            {/* Sidebar */}
            <aside
              className={`w-full sm:w-[320px] sm:h-full h-auto flex justify-start items-center flex-col p-[30px] pt-[50px] overflow-y-auto overflow-x-hidden bg-[#FDF1F5] rounded-2xl border-[2.5px] border-pink-300 shadow-lg ${hasMounted ? "animate-fade-in-up" : ""}`}
              style={{ scrollbarWidth: "thin", scrollbarColor: "#c4c4c4 transparent" }}
            >
              {/* Avatar 可點擊跳回首頁 */}
              <div className="relative w-[120px] h-[120px] mb-6">
                <Link href="/">
                  <Image
                    src={AvatarImg}
                    alt="Avatar"
                    className="w-[120px] h-[120px] rounded-full cursor-pointer hover:scale-105 transition-transform border-4 border-white"
                  />
                </Link>

                {/* SVG 繞圓文字：改在右上角，遠一點點 */}
                <svg
                  className="absolute -top-4 -right-4 pointer-events-none"
                  width="140"
                  height="140"
                  viewBox="0 0 120 120"
                >
                  <defs>
                    <path
                      id="circlePath"
                      d="M60,60 m-50,0 a50,50 0 1,1 100,0 a50,50 0 1,1 -100,0"
                      fill="none"
                    />
                  </defs>
                  <text fill="#ec4899" fontSize="10" fontWeight="bold">
                    <textPath href="#circlePath" startOffset="10%">
                      ✨ Click me! ✨ Click me!
                    </textPath>
                  </text>
                </svg>
              </div>
              <h1
                className="max-w-[380px] text-center font-bold animate-fade-in-up"
                style={{ fontFamily: "'Noto Sans TC', sans-serif", color: "text-pink-900", animationDelay: "200ms" }}
              >
                盧語宸 Joyce Lu
              </h1>

              <p
                className="max-w-[380px] text-center font-bold animate-fade-in-up"
                style={{ fontFamily: "'Noto Sans TC', sans-serif", color: "text-pink-900", animationDelay: "300ms" }}
              >
                NCCU PFxDCT | ISFJ
              </p>

              {/* 社群連結：圓形白底粉紅 icon */}
              <div className="flex gap-3 mt-6 mb-8 animate-fade-in-up" style={{ animationDelay: "400ms" }}>
                {[
                  "facebook",
                  "instagram",
                  "linkedin",
                  "threads"
                ].map((platform) => (
                  <a
                    key={platform}
                    href={
                      platform === "facebook"
                        ? "https://www.facebook.com/profile.php?id=100004034598913"
                        : platform === "instagram"
                        ? "https://www.instagram.com/cdebpm.1028_/"
                        : platform === "linkedin"
                        ? "https://www.linkedin.com/in/chubbyc/"
                        : "https://www.threads.net/@cdebpm.1028_?xmt=AQGzJbdP6FydgiolF5hoZp5e1gYeLYlUDYXTtoYNjdfFOdU"
                    }
                    target="_blank"
                    rel="noopener noreferrer"
                    className="w-[40px] h-[40px] bg-white rounded-full flex items-center justify-center shadow hover:scale-110 transition"
                  >
                    <img
                      src={`../${platform}.png`}
                      alt={platform}
                      className="w-[24px] h-[24px] object-contain"
                    />
                  </a>
                ))}
              </div>

              {/* 頁面切換 */}
              <div
                className="w-full flex flex-col gap-4 text-[20px] animate-fade-in-up"
                style={{ fontFamily: "font-semibold mb-1", fontWeight: 900, animationDelay: "500ms" }}
              >
                <Link href="/about">
                  <div className="w-[200px] h-[60px] mx-auto bg-[#FADADD] rounded-xl border-[2.5px] border-[#D38EB8] flex items-center justify-center hover:bg-[#F6B0C1] animate-heartbeat transition-all duration-300">
                    ABOUT
                  </div>
                </Link>
                <Link href="/uiuxdesign">
                  <div className="w-[200px] h-[60px] mx-auto bg-[#FADADD] rounded-xl border-[2.5px] border-[#D38EB8] flex items-center justify-center hover:bg-[#F6B0C1] animate-heartbeat transition-all duration-300">
                    UI/UX 設計
                  </div>
                </Link>
                <Link href="/businessproject">
                  <div className="w-[200px] h-[60px] mx-auto bg-[#FADADD] rounded-xl border-[2.5px] border-[#D38EB8] flex items-center justify-center hover:bg-[#F6B0C1] animate-heartbeat transition-all duration-300">
                    商業專案分析
                  </div>
                </Link>
                <Link href="/digitalmkt">
                  <div className="w-[200px] h-[60px] mx-auto bg-[#FADADD] rounded-xl border-[2.5px] border-[#D38EB8] flex items-center justify-center hover:bg-[#F6B0C1] animate-heartbeat transition-all duration-300">
                    數位行銷
                  </div>
                </Link>
                <Link href="/exhibitdesign">
                  <div className="w-[200px] h-[60px] mx-auto bg-[#FADADD] rounded-xl border-[2.5px] border-[#D38EB8] flex items-center justify-center hover:bg-[#F6B0C1] animate-heartbeat transition-all duration-300">
                    策展提案
                  </div>
                </Link>
              </div>
            </aside>

            {/* Main 可捲動 */}
            <main
              className="w-full sm:flex-1 h-full overflow-y-auto bg-transparent rounded-xl border-[2px] border-dashed border-pink-300 shadow p-4 h-36"
              style={{ scrollbarWidth: "thin", scrollbarColor: "#c4c4c4 transparent" }}
            >
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
